# Generated by Django 4.0.4 on 2022-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
